DL-12653 play 3.0 migration
hmrc/deregister-vat pull request #36
Opened 2024-06-03 17:19 UTC by pankaj2453

# Pull Request Checklist
* [ ] Branch is rebased with master
* [ ] Added Unit Tests for changed functionality
* [ ] Ran `sbt clean compile coverage test it:test coverageReport`, all tests pass and coverage meets minimum
* [ ] Checked libraries are up to date with `sbt validate`. (If applicable) library updates are done in a separate, single commit
* [ ] Ran [change-vat-acceptance-tests](https://github.com/hmrc/change-vat-acceptance-tests) (see README of repo)
* [ ] Ran [change-vat-performance-tests](https://github.com/hmrc/change-vat-performance-tests) (see README of repo)
* [ ] (If applicable) raised app-config-* PRs
* [ ] (If applicable) ran Wave test for changes to views
* [ ] (If applicable) added Integration Tests

2024-06-06 10:54 UTC, danny-waughman approved these changes

2024-06-20 16:11 UTC, derickdamoah requested changes

2024-06-20 16:11 UTC, derickdamoah commented on build.sbt
the integration tests need to be move to their own folder like follows:
it < tests < whatever

2024-06-21 09:52 UTC, pankaj2453 commented on project/plugins.sbt
updated

2024-06-21 09:52 UTC, pankaj2453 commented on build.sbt
updated

2024-06-21 14:08 UTC, derickdamoah approved these changes

2024-06-21 14:08 UTC, merged